apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== # base64 encoded value of 'root_password'
  MYSQL_DATABASE: bGVhdmVkYg== # base64 encoded value of 'leavedb'
  MYSQL_USER: bGVhdmV1c2Vy # base64 encoded value of 'leaveuser'
  MYSQL_PASSWORD: bGVhdmVwYXNzd29yZA== # base64 encoded value of 'leavepassword'
